### ISSUE TITLE
Error: _platform_prerequisites() got unexpected keyword argument: explicit_minimum_deployment_os

### ISSUE THREAD

**Issue by cdoky** [bazel-ios/rules_ios#289]
```shell
Traceback (most recent call last):
        File "/private/var/tmp/_bazel_cc/84a980d683caa75312511e7341654fc0/external/build_bazel_rules_ios/rules/precompiled_apple_resource_bundle.bzl", line 57, column 73, in _precompiled_apple_resource_bundle_impl
                platform_prerequisites = platform_support.platform_prerequisites(
        File "/private/var/tmp/_bazel_cc/84a980d683caa75312511e7341654fc0/external/build_bazel_rules_apple/apple/internal/platform_support.bzl", line 68, column 5, in _platform_prerequisites
                def _platform_prerequisites(
Error: _platform_prerequisites() got unexpected keyword argument: explicit_minimum_deployment_os
```

**Comment by cdoky** [comment]
fixed by:
```shell
# git_repository(
#     name = "build_bazel_rules_apple",
#     remote = "https://github.com/bazelbuild/rules_apple.git",
#     tag = "0.31.2",
# )
```
