### ISSUE TITLE
Bazel auto-configured xcode_version is flaky: ERROR: /private/var/tmp/_bazel_runner/c2342bca25695567c8c3f3be166b56b3/external/local_config_cc/BUILD:87:24: in cc_toolchain_config rule @local_config_cc//:darwin_x86_64: 

### ISSUE THREAD

**Issue by jerrymarino** [bazel-ios/rules_ios#361]
This issue is plaguing the CI and also local developers.  It calls `xcode-select -s` each time ( although doesn't have a developer directory ).

```
ERROR: /private/var/tmp/_bazel_runner/c2342bca25695567c8c3f3be166b56b3/external/local_config_cc/BUILD:87:24: in cc_toolchain_config rule @local_config_cc//:darwin_x86_64: 
75
Traceback (most recent call last):
76
	File "/private/var/tmp/_bazel_runner/c2342bca25695567c8c3f3be166b56b3/external/local_config_cc/cc_toolchain_config.bzl", line 495, column 61, in _impl
77
		flags = _deterministic_libtool_flags(ctx) + [
78
	File "/private/var/tmp/_bazel_runner/c2342bca25695567c8c3f3be166b56b3/external/local_config_cc/cc_toolchain_config.bzl", line 53, column 38, in _deterministic_libtool_flags
79
		if _can_use_deterministic_libtool(ctx):
80
	File "/private/var/tmp/_bazel_runner/c2342bca25695567c8c3f3be166b56b3/external/local_config_cc/cc_toolchain_config.bzl", line 45, column 25, in _can_use_deterministic_libtool
81
		if _compare_versions(xcode_version, _SUPPORTS_DETERMINISTIC_MODE) >= 0:
82
	File "/private/var/tmp/_bazel_runner/c2342bca25695567c8c3f3be166b56b3/external/local_config_cc/cc_toolchain_config.bzl", line 38, column 15, in _compare_versions
83
		return dv1.compare_to(apple_common.dotted_version(v2))
```

**Comment by jerrymarino** [comment]
Here's a related Bazel issue: https://github.com/bazelbuild/bazel/issues/13509

**Comment by jerrymarino** [comment]
Details in here on current status https://github.com/bazel-ios/rules_ios/pull/362 and upstream fix
