### ISSUE TITLE
`apple_framework_packing` with `link_dynamic=true` will cause error

### ISSUE THREAD

**Issue by wendyliga** [bazel-ios/rules_ios#702]
```
apple_framework_packaging(
    name = "FooFramework",
    framework_name = "Foo",
    bundle_id = "com.example.foo"
    infoplists = ["Info.Plist"],
    link_dynamic = True,
    deps = [
        "//FooLibraryI",
    ],
    platforms = {"ios": "12.0"},
    transitive_deps = [],
    visibility = ["//visibility:public"],
)
```

the error
```
Error in getattr: 'platform_types' value has no field or method ''
Available attributes: catalyst, ios, macos, tvos, watchos
```

**Comment by thiagohmcruz** [comment]
+1 couldn't find any reference to `platform_types` in `rules_ios` nor in `rules_apple` or the Bazel command line 🤔, a repro would be great!

**Comment by wendyliga** [comment]
@mattrobmattrob @thiagohmcruz  sure, i have created a simple project [here](https://github.com/wendyliga/simple_bazel) and run `bazel build //src/Bar`  to reproduce the issue

this is the full log and the stack trace
```
ERROR: /Users/wendy.liga/Developer/simple_bazel/src/Bar/BUILD:11:26: in apple_framework_packaging rule //src/Bar:Bar: 
Traceback (most recent call last):
        File "/private/var/tmp/_bazel_wendy.liga/8284c4a94ccbbb579b9e33d50d39273c/external/build_bazel_rules_ios/rules/framework.bzl", line 1031, column 48, in _apple_framework_packaging_impl
                bundle_outs = _bundle_dynamic_framework(ctx, is_extension_safe = is_extension_safe, avoid_deps = avoid_deps)
        File "/private/var/tmp/_bazel_wendy.liga/8284c4a94ccbbb579b9e33d50d39273c/external/build_bazel_rules_ios/rules/framework.bzl", line 635, column 84, in _bundle_dynamic_framework
                bundle_name, bundle_extension = bundling_support.bundle_full_name_from_rule_ctx(ctx)
        File "/private/var/tmp/_bazel_wendy.liga/8284c4a94ccbbb579b9e33d50d39273c/external/build_bazel_rules_apple/apple/internal/bundling_support.bzl", line 56, column 55, in _bundle_full_name_from_rule_ctx
                rule_descriptor = rule_support.rule_descriptor(ctx),
        File "/private/var/tmp/_bazel_wendy.liga/8284c4a94ccbbb579b9e33d50d39273c/external/build_bazel_rules_apple/apple/internal/rule_support.bzl", line 867, column 28, in _rule_descriptor
                platform_type = getattr(apple_common.platform_type, ctx.attr.platform_type)
Error in getattr: 'platform_types' value has no field or method ''
Available attributes: catalyst, ios, macos, tvos, watchos
```

**Comment by mattrobmattrob** [comment]
Why are you using `apple_framework_packaging` directly instead of this?
```Starlark
load("@build_bazel_rules_ios//rules:framework.bzl", "apple_framework")

apple_framework(
    name = "Bar",
    srcs = glob(['**/*.swift']),
    bundle_id = "com.example.bar",
    infoplists = ["Info.plist"],
    link_dynamic = True,
    platforms = {"ios": "12.0"},
    visibility = ["//visibility:public"],
)
```
And, similarly, you should be using the `rules_ios.ios_application` [macro](https://github.com/bazel-ios/rules_ios/blob/master/rules/app.bzl) if you want to support packaging in `rules_ios` things:
```
load("@build_bazel_rules_ios//rules:app.bzl", "ios_application")
```

**Comment by mattrobmattrob** [comment]
Additionally, it seems like you're mixing a lot of rules_apple/rules_swift native stuff with rules_ios things. Why are you doing that vs. just using entirely rules_ios? For example, you can swap the `RxRelay` definition over to something like this:

https://github.com/bazel-ios/rules_ios/blob/6f11291e4147185a87f5c65766b31897b9eb4ad7/tests/ios/xcframeworks/Basic/BasicXCFramework/BUILD.bazel#L3-L46

**Comment by wendyliga** [comment]
@mattrobmattrob my usecase is to generate a precompiled framework, you should use `apple_framework_packing` right?
regarding the mixing of the rules, I think the target `//src/Bar` is quite isolated. the repo is exist before, i just reuse it for showing this case.
