### ISSUE TITLE
`raise Exception(f"failed to clonefile {src} to {full_dest}")` when using a specific combination of `apple_framework_packaging` and `link_dynamic = True`

### ISSUE THREAD

**Issue by thiagohmcruz** [bazel-ios/rules_ios#851]
This is a bit 🤯 but hit this internally and managed to get it to repro in `rules_ios`:

* Checkout [this branch](https://github.com/bazel-ios/rules_ios/compare/thiago/failed-to-clone_embedded_bundles_partial-repro)
* Build this `bazel build //tests/ios/app:TestAppWithInfoPlist --define=apple.experimental.tree_artifact_outputs=1`

You'll hit this err:
```sh
ERROR: /Users/thiago/Development/rules_ios/tests/ios/app/BUILD.bazel:273:14: Bundling, processing and signing TestAppWithInfoPlist.__internal__.__test_bundle failed: (Exit 1): bundletool_experimental failed: error executing command (from target //tests/ios/app:TestAppWithInfoPlist.__internal__.__test_bundle) 
  (cd /private/var/tmp/_bazel_thiago/122885c1fe4a2c6ed7635584956dfc9d/execroot/_main && \
  exec env - \
    APPLE_SDK_PLATFORM=iPhoneSimulator \
    APPLE_SDK_VERSION_OVERRIDE=17.2 \
    XCODE_VERSION_OVERRIDE=15.1.0.15C65 \
  bazel-out/darwin_arm64-opt-exec-2B5CBBC6-ST-5a29d6cb7794/bin/external/rules_apple~3.1.1/tools/bundletool/bundletool_experimental bazel-out/ios-sim_arm64-min12.0-applebin_ios-ios_sim_arm64-dbg-ST-583c107f4262/bin/tests/ios/app/TestAppWithInfoPlist.__internal__.__test_bundle-intermediates/bundletool_control.json)
# Configuration: 2aae2c8b6c9a86c2bcbecbffdf541d35bd1e3ea9614340c49e0de0b26ab2c255
# Execution platform: @local_config_platform//:host
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_thiago/122885c1fe4a2c6ed7635584956dfc9d/execroot/_main/bazel-out/darwin_arm64-opt-exec-2B5CBBC6-ST-5a29d6cb7794/bin/external/rules_apple~3.1.1/tools/bundletool/bundletool_experimental.runfiles/rules_apple~3.1.1/tools/bundletool/bundletool_experimental.py", line 310, in <module>
    _main(sys.argv[1])
  File "/private/var/tmp/_bazel_thiago/122885c1fe4a2c6ed7635584956dfc9d/execroot/_main/bazel-out/darwin_arm64-opt-exec-2B5CBBC6-ST-5a29d6cb7794/bin/external/rules_apple~3.1.1/tools/bundletool/bundletool_experimental.runfiles/rules_apple~3.1.1/tools/bundletool/bundletool_experimental.py", line 302, in _main
    bundler.run()
  File "/private/var/tmp/_bazel_thiago/122885c1fe4a2c6ed7635584956dfc9d/execroot/_main/bazel-out/darwin_arm64-opt-exec-2B5CBBC6-ST-5a29d6cb7794/bin/external/rules_apple~3.1.1/tools/bundletool/bundletool_experimental.runfiles/rules_apple~3.1.1/tools/bundletool/bundletool_experimental.py", line 138, in run
    self._add_files(f['src'], f['dest'], f.get('executable', False),
  File "/private/var/tmp/_bazel_thiago/122885c1fe4a2c6ed7635584956dfc9d/execroot/_main/bazel-out/darwin_arm64-opt-exec-2B5CBBC6-ST-5a29d6cb7794/bin/external/rules_apple~3.1.1/tools/bundletool/bundletool_experimental.runfiles/rules_apple~3.1.1/tools/bundletool/bundletool_experimental.py", line 170, in _add_files
    self._copy_file(fsrc, fdest, executable, bundle_root)
  File "/private/var/tmp/_bazel_thiago/122885c1fe4a2c6ed7635584956dfc9d/execroot/_main/bazel-out/darwin_arm64-opt-exec-2B5CBBC6-ST-5a29d6cb7794/bin/external/rules_apple~3.1.1/tools/bundletool/bundletool_experimental.runfiles/rules_apple~3.1.1/tools/bundletool/bundletool_experimental.py", line 226, in _copy_file
    raise Exception(f"failed to clonefile {src} to {full_dest}")
Exception: failed to clonefile bazel-out/ios-sim_arm64-min12.0-applebin_ios-ios_sim_arm64-dbg-ST-674860435576/bin/tests/ios/app/FW.framework/FW to bazel-out/ios-sim_arm64-min12.0-applebin_ios-ios_sim_arm64-dbg-ST-583c107f4262/bin/tests/ios/app/TestAppWithInfoPlist.__internal__.__test_bundle_archive-root/TestAppWithInfoPlist.xctest/Frameworks/FW.framework/FW
Target //tests/ios/app:TestAppWithInfoPlist failed to build
```

Notes:

* Adding adding `errno.EEXIST` [here](https://github.com/bazelbuild/rules_apple/blob/cc396794ccc67622d336f897ec826927f5502db7/tools/bundletool/bundletool_experimental.py#L222) in `rules_apple` bypasses the problem and since this seems to be an issue in `rules_ios` custom stuff (framework packaging rule and `link_dynamic`) I don't think we should propose anything upstream
* In the repro branch, the `AppWithInfoPlist_framework_unlinked` mimics something we use internally ([but similar to this one too](https://github.com/bazel-ios/rules_ios/blob/005c2b39862af3843cfe0ab1d37ac8c1c7bccc72/tests/ios/unit-test/test-imports-app/BUILD.bazel#L50))
* In the repro branch actions that "fix" the issue (added comments in the repro branch too about this):
  * Not adding the `*_framework_unlinked` target as a dep
  * Setting `link_dynamic = False`
  * Commenting out [this block](https://github.com/bazel-ios/rules_ios/blob/005c2b39862af3843cfe0ab1d37ac8c1c7bccc72/rules/framework.bzl#L823-L830) (which is part of the `link_dynamic` logic) 
  
Still investigating but any insights appreciated.

**Comment by thiagohmcruz** [comment]
If I rebase the repro branch the issue is gone 🤔 (🎉 ?). It was a couple of commits behind so maybe the latest transitions related changes have fixed it.

**Comment by thiagohmcruz** [comment]
Closing this as it's not happening in `main` anymore.
